apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mongo-volume
spec:
 accessModes:
 - ReadWriteOnce
 resources:
  requests:
   storage: 5Gi
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: mongo
 labels:
  app: mongo
  role: service
spec:
 replicas: 1
 selector: 
  matchLabels:
   app: mongo
   role: service
 serviceName: mongo
 template: 
  metadata:
   labels:
    app: mongo
    role: service
  spec:
   containers:
   - name: mongo
     image: mongo:4.2-bionic
     ports:
     - containerPort: 27017
       name: mongo
       protocol: TCP
     volumeMounts:
     - mountPath: "/data/db"
       name: mongo-volume
   volumes:
    - name: mongo-volume
      persistentVolumeClaim:
       claimName: mongo-volume
---
apiVersion: v1
kind: Service
metadata:
 name: mongo
spec:
 ports:
 - protocol: TCP
   port: 27017
   targetPort: 27017
 selector:
   app: mongo
 type: ClusterIP
