apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: postgres-volume
spec:
 accessModes:
 - ReadWriteOnce
 resources:
  requests:
   storage: 5Gi
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: postgres
 labels:
  app: postgres
  role: service
spec:
 replicas: 1
 selector: 
  matchLabels:
   app: postgres
   role: service
 serviceName: postgres
 template: 
  metadata:
   labels:
    app: postgres
    role: service
  spec:
   containers:
   - name: postgres
     image: postgres:latest
     env:
     - name: POSTGRES_USER
       value: postgres
     - name: POSTGRES_PASSWORD
       value: postgres
     - name: POSTGRES_DB
       value: postgresdb
     - name: PGDATA
       value: /var/lib/postgresql/data/pgdata
     ports:
     - containerPort: 5432
       name: postgres
       protocol: TCP
     volumeMounts:
     - mountPath: "/var/lib/postgresql/data"
       name: postgres-volume
   volumes:
    - name: postgres-volume
      persistentVolumeClaim:
       claimName: postgres-volume
---
apiVersion: v1
kind: Service
metadata:
 name: postgres
spec:
 ports:
 - protocol: TCP
   port: 5432
   targetPort: 5432
 selector:
   app: postgres
 type: ClusterIP
